#!/bin/bash

MAKETHREADS=4
ARCH=arm
CROSS_COMPILE=/opt/linaro-4.9_2014.11/bin/arm-linux-gnueabihf-
INSTALL_MOD_PATH=output

rm -R $INSTALL_MOD_PATH/*
rm arch/arm/boot/dt.img
rm arch/arm/boot/zImage-dtb
rm arch/arm/mach-msm/smd_rpc_sym.c
make -j$MAKETHREADS ARCH=$ARCH CROSS_COMPILE=$CROSS_COMPILE INSTALL_MOD_PATH=$INSTALL_MOD_PATH clean
